common/urls.py
from .views import IndexView, LoginView, LogoutView, IndexJapanView, IndexPakistanView, IndexPhilipineView
from common.japan_stock_logs import DailyStockLogs, MonthlyStockLogs
from common.pak_stock_logs import PakDailyStockLogs, PakMonthlyStockLogs
from common.philip_stock_logs import PhilipDailyStockLogs, PhilipMonthlyStockLogs
from django.urls import path


urlpatterns = [
    path('', IndexView.as_view(), name='home'),
    path('japan', IndexJapanView.as_view(), name='japan_index'),
    path('pak', IndexPakistanView.as_view(), name='pak_index'),
    path('philip', IndexPhilipineView.as_view(), name='philip_index'),
    path('login', LoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('japan/logs/daily', DailyStockLogs.as_view(), name='daily_logs'),
    path('japan/logs/monthly', MonthlyStockLogs.as_view(), name='monthly_logs'),
    path('pak/logs/daily', PakDailyStockLogs.as_view(), name='pak_daily_logs'),
	path('pak/logs/monthly', PakMonthlyStockLogs.as_view(), name='pak_monthly_logs'),
    path('philip/logs/daily', PhilipDailyStockLogs.as_view(), name='philip_daily_logs'),
	path('philip/logs/monthly', PhilipMonthlyStockLogs.as_view(), name='philip_monthly_logs'),
]

partum_jci/urls.py
from django.contrib import admin
from django.urls import path, include
from common.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('common/', include(('common.urls', 'common'), namespace='common')),
    path('japan/inventory/', include(('japan_inventory.urls', 'japan_inventory'), namespace='japan_inventory')),
    path('philip/inventory/', include(('philip_inventory.urls', 'philip_inventory'), namespace='philip_inventory')),
    path('pak/inventory/', include(('pak_inventory.urls', 'pak_inventory'), namespace='pak_inventory')),
    path('', IndexView.as_view(), name='home'),

]

philip_inventory/urls.py
from django.urls import path
from philip_inventory.stock_views import (
    AddCarBrand, CarBrandList, DeleteCarBrand, AddCarStock,
    CarStockList, DeleteCarStock, UpdateCarStockIn, AddCarParts,
    CarPartsList, DeleteCarPartsStock, CarStockOutList
)
from philip_inventory.expense_views import (
    AddExpense, ExpenseList, UpdateExpense, DeleteExpense
)
from philip_inventory.employee_views import (
    AddEmployee, EmployeeList, UpdateEmployee, DeleteEmployee,
    EmployeeSalaryFormView, EmployeeSalaryListView, DeleteEmployeeSalary
)
from philip_inventory.customer_views import (
    AddCustomer, CustomerList, UpdateCustomer, DeleteCustomer, CustomerLedgerListView, DeleteCustomerLedger, DebitCustomerLedgerFormView, CreditCustomerLedgerFormView
)
from philip_inventory.bank_views import (AddBank, BankList,DeleteBank, BankLedgerListView, DeleteBankLedger, DebitBankLedgerFormView, CreditBankLedgerFormView)
from philip_inventory.car_parts_invoice_views import (CarPartsInvoiceListView, CarPartsCreateInvoiceTemplateView,CarPartsProductListAPIView, CarPartsGenerateInvoiceAPIView, CarPartsInvoiceDetailTemplateView)

from pak_inventory.invoice_views import (
    InvoiceListView, CreateInvoiceTemplateView, ProductListAPIView, GenerateInvoiceAPIView, InvoiceDetailTemplateView
)
from philip_inventory.invoice_views import (
    InvoiceListView, CreateInvoiceTemplateView, ProductListAPIView, GenerateInvoiceAPIView, InvoiceDetailTemplateView,
    DeleteInvoice
)
from philip_inventory.reports import (MonthlyReports)

urlpatterns = [
    path('add/expense/', AddExpense.as_view(), name='expense_add'),
    path('list/expense/', ExpenseList.as_view(), name='expense_list'),
    path('delete/expense/<int:pk>/', DeleteExpense.as_view(), name='expense_delete'),
    path('update/expense/<int:pk>/', UpdateExpense.as_view(), name='expense_update'),
    path('add/employee/', AddEmployee.as_view(), name='add_employee'),
    path('list/employee/', EmployeeList.as_view(), name='employee_list'),
    path('update/employee/<int:pk>/', UpdateEmployee.as_view(), name='employee_update'),
    path('delete/employee/<int:pk>/', DeleteEmployee.as_view(), name='employee_delete'),
    path('employee/salary/<int:pk>/', EmployeeSalaryFormView.as_view(), name='employee_salary'),
    path('employee/salary/detail/<int:pk>/', EmployeeSalaryListView.as_view(), name='employee_salary_detail'),
    path('delete/employee/salary/detail/<int:pk>/', DeleteEmployeeSalary.as_view(), name='delete_employee_salary'),
    path('add/car/brand/', AddCarBrand.as_view(), name='add_car_brand'),
    path('list/brand/', CarBrandList.as_view(), name='list_car_brand'),
    path('delete/<int:pk>/', DeleteCarBrand.as_view(), name='delete_car_brand'),
    path('add/car/stock/in/', AddCarStock.as_view(), name='add_car_stockin'),
    path('car/stock/in/list/', CarStockList.as_view(), name='car_stock_list'),
    path('car/stock/out/list/', CarStockOutList.as_view(), name='car_stock_out_list'),
    path('car/stock/<int:pk>/delete/', DeleteCarStock.as_view(), name='delete_car_stockin'),
    path('update/car/<int:pk>/stock/in/', UpdateCarStockIn.as_view(), name='update_car_stockin'),
    path('add/car/parts/', AddCarParts.as_view(), name='add_car_parts'),
    path('list/car/parts/', CarPartsList.as_view(), name='list_car_parts'),
    path('delete/<int:pk>/car/parts/', DeleteCarPartsStock.as_view(), name='delete_car_parts'),
    path('add/customer/', AddCustomer.as_view(), name='add_customer'),
    path('list/customer/', CustomerList.as_view(), name='customer_list'),
    path('update/customer/<int:pk>/', UpdateCustomer.as_view(), name='customer_update'),
    path('delete/customer/<int:pk>/', DeleteCustomer.as_view(), name='customer_delete'),
    path('list/invoice/', InvoiceListView.as_view(), name='invoice_list'),
    path('add/invoice/customer/', CreateInvoiceTemplateView.as_view(), name='add_invoice'),
    path('product/invoice/customer/api/', ProductListAPIView.as_view(), name='product_api'),
    path('generate/invoice/api/', GenerateInvoiceAPIView.as_view(), name='generate_invoice'),
    path("invoice/<int:pk>/detail/", InvoiceDetailTemplateView.as_view(), name='invoice_detail'),
    path("invoice/<int:pk>/delete/", DeleteInvoice.as_view(), name='invoice_delete'),
    path('<int:pk>/ledger/delete', DeleteCustomerLedger.as_view(), name='delete_ledger'),
    path('<int:pk>/ledger/list/', CustomerLedgerListView.as_view(), name='ledger_list'),
    path('<int:pk>/ledger/debit/', DebitCustomerLedgerFormView.as_view(), name='ledger_debit'),
    path('<int:pk>/ledger/credit/', CreditCustomerLedgerFormView.as_view(), name='ledger_credit'),
    path('add/bank/', AddBank.as_view(), name='add_bank'),
    path('list/bank/', BankList.as_view(), name='bank_list'),
    path('delete/bank/<int:pk>/', DeleteBank.as_view(), name='bank_delete'),
    path('bank/<int:pk>/ledger/list/', BankLedgerListView.as_view(), name='bank_ledger_list'),
    path('bank/<int:pk>/ledger/debit/', DebitBankLedgerFormView.as_view(), name='bank_ledger_debit'),
    path('bank/<int:pk>/ledger/credit/', CreditBankLedgerFormView.as_view(), name='bank_ledger_credit'),
    path('bank/<int:pk>/ledger/delete', DeleteBankLedger.as_view(), name='bank_delete_ledger'),
    path('list/invoice/car/parts/sell/', CarPartsInvoiceListView.as_view(), name='invoice_list_car_parts'),
    path('add/invoice/customer/car/parts/', CarPartsCreateInvoiceTemplateView.as_view(), name='add_invoice_car_parts'),
    path('product/invoice/customer/api/car/parts/', CarPartsProductListAPIView.as_view(), name='product_api_car_parts'),
    path('generate/invoice/api/car/parts/', CarPartsGenerateInvoiceAPIView.as_view(), name='generate_invoice_car_parts'),
    path("invoice/<int:pk>/detail/car/parts/", CarPartsInvoiceDetailTemplateView.as_view(), name='invoice_detail_car_parts'),
    path('reports/monthly', MonthlyReports.as_view(), name='reports'),
    
]

philip_inventory/forms.py
from django import forms
from philip_inventory.models import (
    CarBrand, StockIn, StockOut, CarBuyPart, Expense, Employee, EmployeeSalary, Customer, Invoice,
    CustomerLedger, Bank, BankLedger, CarPartsInvoice, CarPartsStockOut
)


######## Bank###########
class BankForm(forms.ModelForm):
    class Meta:
        model = Bank
        fields = '__all__'

class BankLedgerForm(forms.ModelForm):
    class Meta:
        model = BankLedger
        fields = '__all__'
################# end bank#####################


# ********** starting Expense Forms ****************
class ExpenseFormView(forms.ModelForm):
    class Meta:
        model = Expense
        fields = '__all__'
# *********** ending Expense Forms****************

class CarBrandForm(forms.ModelForm):
    class Meta:
        model = CarBrand
        fields = '__all__'

class StockInForm(forms.ModelForm):
    class Meta:
        model = StockIn
        fields = '__all__'

class StockOutForm(forms.ModelForm):
    class Meta:
        model = StockOut
        fields = '__all__'

class CarBuyPartForm(forms.ModelForm):
    class Meta:
        model = CarBuyPart
        fields = '__all__'


# ********** starting Employee Forms ****************
class EmployeeFormView(forms.ModelForm):
    class Meta:
        model = Employee
        fields = '__all__'
# *********** ending Employee Forms****************


# ********** starting Employee Salary Forms ****************
class EmployeeSalaryForm(forms.ModelForm):
    class Meta:
        model = EmployeeSalary
        fields = '__all__'
# *********** ending Employee Salary Forms****************

# ************ Starting Customer Forms **************
class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = '__all__'

class CustomerLedgerForm(forms.ModelForm):
    class Meta:
        model = CustomerLedger
        fields = '__all__'
# *********** Ending Customer Forms *****************


class InvoiceForm(forms.ModelForm):
    class Meta:
        model = Invoice
        fields = '__all__'


class CarPartsInvoiceForm(forms.ModelForm):
    class Meta:
        model = CarPartsInvoice
        fields = '__all__'


class CarPartsStockoutForm(forms.ModelForm):
    class Meta:
        model = CarPartsStockOut
        fields = '__all__'

philip_inventory/views.py
from django.shortcuts import render

# Create your views here.

templates/philip_inventory/monthly_reports.html
{% extends 'philip_inventory/philip_base.html' %}
{% block reports %}active{% endblock %}
{% block monthly_reports %}active{% endblock %}

{% load static %}

{% block content %}
    <button type="button" class="btn btn-primary print-invoice-btn" onclick="PrintInvoice('print-invoice')" style="margin-left:10px">Print </button>
    <div class="content-wrapper">
        <section class="content-header">
            <ol class="breadcrumb">
                <li><a href="{% url 'common:philip_index' %}"><i class="fa fa-dashboard"></i> Home</a></li>
                <li class="active">Monthly Reports</li>
            </ol>
        </section>
        <section class="content">
            <div class="row">
                            <h3 class="box-title text-center">Monthly Sales Reports</h3>
                <!-- /.col -->
            </div>
            <div class="box">
                <div class="box-body">
                    <div class=" print-invoice" id="print-invoice">
                        <div class="col-md-12">
                            <br>
                            <div class="content-panel table-responsive">
                                <table class="table table-striped table-advance table-hover table-bordered item-table">
                                    <thead>
                                    <tr>
                                        <th>Date</th>
                                        <th>Total Customer</th>
                                        <th>Total Car Quantity</th>
                                        <th>Grand Total</th>
                                        <th>Total Cash Payment</th>
                                        <th>Total Credit Amount </th>
                                        <th>Total Debit Amount</th>
                                        <th>Total Expense Amounts</th>
                                        <th>Grand Total Car Parts</th>
                                        <th>Total Cash Payment Car Parts</th>
                                        <th>Total Quantity Car Parts</th>
                                    </tr>
                                    </thead>
                                    <tbody class="product-table-body">
                                    {% for result in results %}
                                        {% if not result.grand_total == 0 %}
                                            <tr>
                                                <td>{{ result.date}}</td>
                                                <td>{{ result.total_customer }}</td>
                                                <td>{{ result.total_quantity|floatformat:-2 }}</td>
                                                <td>{{ result.grand_total|floatformat:'-2' }}</td>
                                                <td>{{ result.total_cash_payment|floatformat:'-2' }}</td>
                                                <td>{{ result.total_credit_amount|floatformat:'-2' }}</td>
                                                <td>{{ result.total_debit_amount|floatformat:'-2' }}</td>
                                                <td>{{ result.total_expense_amount|floatformat:'-2' }}</td>
                                                <td>{{ result.grand_total_car_parts|floatformat:'-2' }}</td>
                                                <td>{{ result.total_cash_payment_car_parts|floatformat:'-2' }}</td>
                                                <td>{{ result.total_quantity_car_parts|floatformat:'-2' }}</td>

                                            </tr>
                                        {% endif %}
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
{% endblock %}

templates/philip_inventory/philip_base.html
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Philippines Inventory | Partum Solutions </title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="stylesheet" href="{% static 'bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'bower_components/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'bower_components/Ionicons/css/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'bower_components/jvectormap/jquery-jvectormap.css' %}">
    <link rel="stylesheet" href="{% static 'dist/css/AdminLTE.min.css' %}">
    <link rel="stylesheet" href="{% static 'dist/css/skins/_all-skins.min.css' %}">

    <!-- Google Font -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

    <header class="main-header">

        <!-- Logo -->
        <a href="#" class="logo">
            <!-- mini logo for sidebar mini 50x50 pixels -->
            <span class="logo-mini"><b>Philippines Inventory</b></span>
            <!-- logo for regular state and mobile devices -->
            <span class="logo-lg"><b>Partum</b>JCI</span>
        </a>

        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top">
            <!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                <span class="sr-only">Toggle navigation</span>
            </a>

        </nav>
    </header>
    <!-- Left side column. contains the logo and sidebar -->
    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
            <!-- search form -->
            <ul class="sidebar-menu" data-widget="tree">
                <li class="header">Main Navigation</li>
                <li class="treeview {% block car_brand %}{% endblock %}">
                    <a href="#">
                        <i class="fa fa-car"></i> <span>Car Brands</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="{% block add_car_brand %}{% endblock %}"><a href="{% url 'philip_inventory:add_car_brand' %}"><i class="fa fa-circle-o"></i>Add Car Brands</a></li>
                        <li class="{% block list_car_brand %}{% endblock %}"><a href="{% url 'philip_inventory:list_car_brand' %}"><i class="fa fa-circle-o"></i>Car Brand List</a></li>
                    </ul>
                </li>
                <li class="treeview {% block stock %}{% endblock %}">
                    <a href="#">
                        <i class="fa fa-stack-overflow"></i> <span>Stock</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="{% block stock_create %}{% endblock %}"><a href="{% url 'philip_inventory:add_car_stockin' %}"><i class="fa fa-circle-o"></i>Add Car Stock</a></li>
                        <li class="{% block stock_list %}{% endblock %}"><a href="{% url 'philip_inventory:car_stock_list' %}"><i class="fa fa-circle-o"></i>Stock In List</a></li>
                        <li class="{% block stock_out_list %}{% endblock %}"><a href="{% url 'philip_inventory:car_stock_out_list' %}"><i class="fa fa-circle-o"></i>Stock Out List</a></li>
                    </ul>
                </li>
                <li class="treeview {% block parts %}{% endblock %}">
                    <a href="#">
                        <i class="fa fa-cog fa-spin fa-fw"></i> <span>Car Parts Stock</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="{% block add_car_parts %}{% endblock %}"><a href="{% url 'philip_inventory:add_car_parts' %}"><i class="fa fa-circle-o"></i>Add Car Parts Stock</a></li>
                        <li class="{% block car_parts_list %}{% endblock %}"><a href="{% url 'philip_inventory:list_car_parts' %}"><i class="fa fa-circle-o"></i>Car Parts List</a></li>
                    </ul>
                </li>
                <li class="header">Expenses</li>
                <li class="treeview {% block expense %}{% endblock %}">
                    <a href="#">
                        <i class="fa fa-money"></i> <span>Expense System</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="{% block add_expense %}{% endblock %}"><a href="{% url 'philip_inventory:expense_add' %}"><i class="fa fa-circle-o"></i> <span>Add Expense</span></a></li>
                        <li class="{% block expense_list %}{% endblock %}"><a href="{% url 'philip_inventory:expense_list' %}"><i class="fa fa-circle-o"></i>Expense List</a></li>
                    </ul>
                </li>
                <li class="header">Customer</li>
                <li class="treeview {% block customer %}{% endblock %}">
                    <a href="#">
                        <i class="fa fa-user"></i> <span>Customer</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="{% block add_customer %}{% endblock %}"><a href="{% url 'philip_inventory:add_customer' %}"><i class="fa fa-circle-o"></i> <span>Add Customer</span></a></li>
                        <li class="{% block customer_list %}{% endblock %}"><a href="{% url 'philip_inventory:customer_list' %}"><i class="fa fa-circle-o"></i>Customer List</a></li>
                    </ul>
                </li>
                <li class="header">Employee</li>
                <li class="treeview {% block employee %}{% endblock %}">
                    <a href="#">
                        <i class="fa fa-users"></i> <span>Employee</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="{% block add_employee %}{% endblock %}"><a href="{% url 'philip_inventory:add_employee' %}"><i class="fa fa-circle-o"></i> <span>Add Employee</span></a></li>
                        <li class="{% block employee_list %}{% endblock %}"><a href="{% url 'philip_inventory:employee_list' %}"><i class="fa fa-circle-o"></i>Employee List</a></li>
                    </ul>
                </li>
                <li class="header">Bank</li>
                <li class="treeview {% block bank %}{% endblock %}">
                    <a href="#">
                        <i class="fa fa-bank"></i> <span>Bank</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="{% block add_bank %}{% endblock %}"><a href="{% url 'philip_inventory:add_bank' %}"><i class="fa fa-circle-o"></i> <span>Add Bank</span></a></li>
                        <li class="{% block bank_list %}{% endblock %}"><a href="{% url 'philip_inventory:bank_list' %}"><i class="fa fa-circle-o"></i>Bank List</a></li>
                    </ul>
                </li>
                <li class="header">Sales</li>
                <li class="treeview {% block sales %}{% endblock %}">
                    <a href="#">
                        <i class="fa fa-shopping-cart"></i> <span>Sales</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="{% block sales_add %}{% endblock %}"><a href="{% url 'philip_inventory:add_invoice' %}"><i class="fa fa-circle-o"></i> <span>Add Invoice</span></a></li>
                        <li class="{% block sales_list %}{% endblock %}"><a href="{% url 'philip_inventory:invoice_list' %}"><i class="fa fa-circle-o"></i>Invoice List</a></li>
                    </ul>
                </li>
                <li class="header">Car Parts Sales</li>
                <li class="treeview {% block car_parts %}{% endblock %}">
                    <a href="#">
                        <i class="fa fa-shopping-cart "></i> <span>Car Parts Sales</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="{% block sales_add_car_parts %}{% endblock %}"><a href="{% url 'philip_inventory:add_invoice_car_parts' %}"><i class="fa fa-circle-o"></i> <span>Add Car Parts Invoice</span></a></li>
                        <li class="{% block sales_list_car_parts %}{% endblock %}"><a href="{% url 'philip_inventory:invoice_list_car_parts' %}"><i class="fa fa-circle-o"></i>Car Parts Invoice List</a></li>
                    </ul>
                </li>
                <li class="header">Logs & Reports</li>
                <li class="treeview {% block stock_logs %}{% endblock %}">
                    <a href="#">
                        <i class="fa fa-history fa-spin fa-fw"></i> <span>Stock Logs</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="{% block daily_stock_logs %}{% endblock %}"><a href="{% url 'common:philip_daily_logs' %}"><i class="fa fa-circle-o"></i> <span>Daily Logs</span></a></li>
                        <li class="{% block monthly_stock_logs %}{% endblock %}"><a href="{% url 'common:philip_monthly_logs' %}"><i class="fa fa-circle-o"></i>Monthly Logs</a></li>
                    </ul>
                </li>
                <li class="treeview {% block reports %}{% endblock %}">
                    <a href="#">
                        <i class="fa fa-copy"></i> <span>Reports</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="{% block monthly_reports %}{% endblock %}"><a href="{% url 'philip_inventory:reports' %}"><i class="fa fa-circle-o"></i> <span>Monthly Reports</span></a></li>
                    </ul>
                </li>
                <li class="header">User</li>
                 <li>
                    <a href="{% url 'common:logout' %}"><i class="fa fa-sign-out"></i> <span>Logout</span></a>
                </li>
            </ul>
        </section>
    </aside>

    <!-- Content Wrapper. Contains page content -->
    {% block content %}{% endblock %}
    <!-- /.content-wrapper -->

    <footer class="main-footer">
        <div class="pull-right hidden-xs">
            <b>Version</b> 2.4.18
        </div>
        <strong>Copyright &copy; 2014-2020 <a href="#">Partum Solutions</a>.</strong> All rights
        reserved.
    </footer>
</div>

{% block script %}
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/jquery-1.8.3.min.js' %}"></script>
    <script src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'bower_components/fastclick/lib/fastclick.js' %}"></script>
    <script src="{% static 'dist/js/adminlte.min.js' %}"></script>
    <script src="{% static 'bower_components/jquery-sparkline/dist/jquery.sparkline.min.js' %}"></script>
    <script src="{% static 'plugins/jvectormap/jquery-jvectormap-1.2.2.min.js' %}"></script>
    <script src="{% static 'plugins/jvectormap/jquery-jvectormap-world-mill-en.js' %}"></script>
    <script src="{% static 'bower_components/jquery-slimscroll/jquery.slimscroll.min.js' %}"></script>
    <script src="{% static 'bower_components/chart.js/Chart.js' %}"></script>
    <script src="{% static 'dist/js/demo.js' %}"></script>

    <script>
        var notification_count = 0;
        {% for p in p_n %}
            {% if p.product_available_items <= p.notify_qty %}
                    notification_count += 1;
            {% endif %}
        {% endfor %}

        $('.notification_count').text(notification_count);
    </script>

{% endblock %}
</body>
</html>

templates/philip_inventory/philip_home.html
{% extends "philip_inventory/philip_base.html"%}
{% block content %}
{% load static %}
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Dashboard
        <small>Version 2.0</small>
      </h1>
      <ol class="breadcrumb">
        {% if request.user.user_profile.user_type == request.user.user_profile.USER_TYPE_ADMIN %}
        <li class="active"><a href="{% url 'home' %}">Main Dashboard</a></li>
        {% endif %}
        <li><a href="{% url 'common:philip_index' %}"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Philippines Dashboard</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <!-- Info boxes -->
      
      <!-- /.row -->

      <!-- <div class="row">
        <div class="col-md-12">
          <div class="box">
            <div class="box-header with-border">
              <h3 class="box-title">Monthly Recap Report</h3>
              <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
                <div class="btn-group">
                  <button type="button" class="btn btn-box-tool dropdown-toggle" data-toggle="dropdown">
                    <i class="fa fa-wrench"></i></button>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="#">Action</a></li>
                    <li><a href="#">Another action</a></li>
                    <li><a href="#">Something else here</a></li>
                    <li class="divider"></li>
                    <li><a href="#">Separated link</a></li>
                  </ul>
                </div>
                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
              </div>
            </div>
             /.box-header -->

        <!-- /.col -->

      <!-- /.row -->

            <!-- /.box-body -->

            <!-- /.box-footer -->

          <!-- /.box -->

        <!-- /.col -->

      <!-- /.row -->
    </section>
    <!-- /.content -->
  </div>
{% endblock %}