common/urls.py
from .views import IndexView, LoginView, LogoutView, IndexJapanView, IndexPakistanView, IndexPhilipineView
from common.japan_stock_logs import DailyStockLogs, MonthlyStockLogs
from common.pak_stock_logs import PakDailyStockLogs, PakMonthlyStockLogs
from common.philip_stock_logs import PhilipDailyStockLogs, PhilipMonthlyStockLogs
from django.urls import path


urlpatterns = [
    path('', IndexView.as_view(), name='home'),
    path('japan', IndexJapanView.as_view(), name='japan_index'),
    path('pak', IndexPakistanView.as_view(), name='pak_index'),
    path('philip', IndexPhilipineView.as_view(), name='philip_index'),
    path('login', LoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('japan/logs/daily', DailyStockLogs.as_view(), name='daily_logs'),
    path('japan/logs/monthly', MonthlyStockLogs.as_view(), name='monthly_logs'),
    path('pak/logs/daily', PakDailyStockLogs.as_view(), name='pak_daily_logs'),
	path('pak/logs/monthly', PakMonthlyStockLogs.as_view(), name='pak_monthly_logs'),
    path('philip/logs/daily', PhilipDailyStockLogs.as_view(), name='philip_daily_logs'),
	path('philip/logs/monthly', PhilipMonthlyStockLogs.as_view(), name='philip_monthly_logs'),
]

partum_jci/urls.py
from django.contrib import admin
from django.urls import path, include
from common.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('common/', include(('common.urls', 'common'), namespace='common')),
    path('japan/inventory/', include(('japan_inventory.urls', 'japan_inventory'), namespace='japan_inventory')),
    path('philip/inventory/', include(('philip_inventory.urls', 'philip_inventory'), namespace='philip_inventory')),
    path('pak/inventory/', include(('pak_inventory.urls', 'pak_inventory'), namespace='pak_inventory')),
    path('', IndexView.as_view(), name='home'),

]

philip_inventory/urls.py
from django.urls import path
from philip_inventory.stock_views import (
    AddCarBrand, CarBrandList, DeleteCarBrand, AddCarStock,
    CarStockList, DeleteCarStock, UpdateCarStockIn, AddCarParts,
    CarPartsList, DeleteCarPartsStock, CarStockOutList
)
from philip_inventory.expense_views import (
    AddExpense, ExpenseList, UpdateExpense, DeleteExpense
)
from philip_inventory.employee_views import (
    AddEmployee, EmployeeList, UpdateEmployee, DeleteEmployee,
    EmployeeSalaryFormView, EmployeeSalaryListView, DeleteEmployeeSalary
)
from philip_inventory.customer_views import (
    AddCustomer, CustomerList, UpdateCustomer, DeleteCustomer, CustomerLedgerListView, DeleteCustomerLedger, DebitCustomerLedgerFormView, CreditCustomerLedgerFormView
)
from philip_inventory.bank_views import (AddBank, BankList,DeleteBank, BankLedgerListView, DeleteBankLedger, DebitBankLedgerFormView, CreditBankLedgerFormView)
from philip_inventory.car_parts_invoice_views import (CarPartsInvoiceListView, CarPartsCreateInvoiceTemplateView,CarPartsProductListAPIView, CarPartsGenerateInvoiceAPIView, CarPartsInvoiceDetailTemplateView)

from pak_inventory.invoice_views import (
    InvoiceListView, CreateInvoiceTemplateView, ProductListAPIView, GenerateInvoiceAPIView, InvoiceDetailTemplateView
)
from philip_inventory.invoice_views import (
    InvoiceListView, CreateInvoiceTemplateView, ProductListAPIView, GenerateInvoiceAPIView, InvoiceDetailTemplateView,
    DeleteInvoice
)
from philip_inventory.reports import (MonthlyReports)

urlpatterns = [
    path('add/expense/', AddExpense.as_view(), name='expense_add'),
    path('list/expense/', ExpenseList.as_view(), name='expense_list'),
    path('delete/expense/<int:pk>/', DeleteExpense.as_view(), name='expense_delete'),
    path('update/expense/<int:pk>/', UpdateExpense.as_view(), name='expense_update'),
    path('add/employee/', AddEmployee.as_view(), name='add_employee'),
    path('list/employee/', EmployeeList.as_view(), name='employee_list'),
    path('update/employee/<int:pk>/', UpdateEmployee.as_view(), name='employee_update'),
    path('delete/employee/<int:pk>/', DeleteEmployee.as_view(), name='employee_delete'),
    path('employee/salary/<int:pk>/', EmployeeSalaryFormView.as_view(), name='employee_salary'),
    path('employee/salary/detail/<int:pk>/', EmployeeSalaryListView.as_view(), name='employee_salary_detail'),
    path('delete/employee/salary/detail/<int:pk>/', DeleteEmployeeSalary.as_view(), name='delete_employee_salary'),
    path('add/car/brand/', AddCarBrand.as_view(), name='add_car_brand'),
    path('list/brand/', CarBrandList.as_view(), name='list_car_brand'),
    path('delete/<int:pk>/', DeleteCarBrand.as_view(), name='delete_car_brand'),
    path('add/car/stock/in/', AddCarStock.as_view(), name='add_car_stockin'),
    path('car/stock/in/list/', CarStockList.as_view(), name='car_stock_list'),
    path('car/stock/out/list/', CarStockOutList.as_view(), name='car_stock_out_list'),
    path('car/stock/<int:pk>/delete/', DeleteCarStock.as_view(), name='delete_car_stockin'),
    path('update/car/<int:pk>/stock/in/', UpdateCarStockIn.as_view(), name='update_car_stockin'),
    path('add/car/parts/', AddCarParts.as_view(), name='add_car_parts'),
    path('list/car/parts/', CarPartsList.as_view(), name='list_car_parts'),
    path('delete/<int:pk>/car/parts/', DeleteCarPartsStock.as_view(), name='delete_car_parts'),
    path('add/customer/', AddCustomer.as_view(), name='add_customer'),
    path('list/customer/', CustomerList.as_view(), name='customer_list'),
    path('update/customer/<int:pk>/', UpdateCustomer.as_view(), name='customer_update'),
    path('delete/customer/<int:pk>/', DeleteCustomer.as_view(), name='customer_delete'),
    path('list/invoice/', InvoiceListView.as_view(), name='invoice_list'),
    path('add/invoice/customer/', CreateInvoiceTemplateView.as_view(), name='add_invoice'),
    path('product/invoice/customer/api/', ProductListAPIView.as_view(), name='product_api'),
    path('generate/invoice/api/', GenerateInvoiceAPIView.as_view(), name='generate_invoice'),
    path("invoice/<int:pk>/detail/", InvoiceDetailTemplateView.as_view(), name='invoice_detail'),
    path("invoice/<int:pk>/delete/", DeleteInvoice.as_view(), name='invoice_delete'),
    path('<int:pk>/ledger/delete', DeleteCustomerLedger.as_view(), name='delete_ledger'),
    path('<int:pk>/ledger/list/', CustomerLedgerListView.as_view(), name='ledger_list'),
    path('<int:pk>/ledger/debit/', DebitCustomerLedgerFormView.as_view(), name='ledger_debit'),
    path('<int:pk>/ledger/credit/', CreditCustomerLedgerFormView.as_view(), name='ledger_credit'),
    path('add/bank/', AddBank.as_view(), name='add_bank'),
    path('list/bank/', BankList.as_view(), name='bank_list'),
    path('delete/bank/<int:pk>/', DeleteBank.as_view(), name='bank_delete'),
    path('bank/<int:pk>/ledger/list/', BankLedgerListView.as_view(), name='bank_ledger_list'),
    path('bank/<int:pk>/ledger/debit/', DebitBankLedgerFormView.as_view(), name='bank_ledger_debit'),
    path('bank/<int:pk>/ledger/credit/', CreditBankLedgerFormView.as_view(), name='bank_ledger_credit'),
    path('bank/<int:pk>/ledger/delete', DeleteBankLedger.as_view(), name='bank_delete_ledger'),
    path('list/invoice/car/parts/sell/', CarPartsInvoiceListView.as_view(), name='invoice_list_car_parts'),
    path('add/invoice/customer/car/parts/', CarPartsCreateInvoiceTemplateView.as_view(), name='add_invoice_car_parts'),
    path('product/invoice/customer/api/car/parts/', CarPartsProductListAPIView.as_view(), name='product_api_car_parts'),
    path('generate/invoice/api/car/parts/', CarPartsGenerateInvoiceAPIView.as_view(), name='generate_invoice_car_parts'),
    path("invoice/<int:pk>/detail/car/parts/", CarPartsInvoiceDetailTemplateView.as_view(), name='invoice_detail_car_parts'),
    path('reports/monthly', MonthlyReports.as_view(), name='reports'),
    
]

philip_inventory/forms.py
from django import forms
from philip_inventory.models import (
    CarBrand, StockIn, StockOut, CarBuyPart, Expense, Employee, EmployeeSalary, Customer, Invoice,
    CustomerLedger, Bank, BankLedger, CarPartsInvoice, CarPartsStockOut
)


######## Bank###########
class BankForm(forms.ModelForm):
    class Meta:
        model = Bank
        fields = '__all__'

class BankLedgerForm(forms.ModelForm):
    class Meta:
        model = BankLedger
        fields = '__all__'
################# end bank#####################


# ********** starting Expense Forms ****************
class ExpenseFormView(forms.ModelForm):
    class Meta:
        model = Expense
        fields = '__all__'
# *********** ending Expense Forms****************

class CarBrandForm(forms.ModelForm):
    class Meta:
        model = CarBrand
        fields = '__all__'

class StockInForm(forms.ModelForm):
    class Meta:
        model = StockIn
        fields = '__all__'

class StockOutForm(forms.ModelForm):
    class Meta:
        model = StockOut
        fields = '__all__'

class CarBuyPartForm(forms.ModelForm):
    class Meta:
        model = CarBuyPart
        fields = '__all__'


# ********** starting Employee Forms ****************
class EmployeeFormView(forms.ModelForm):
    class Meta:
        model = Employee
        fields = '__all__'
# *********** ending Employee Forms****************


# ********** starting Employee Salary Forms ****************
class EmployeeSalaryForm(forms.ModelForm):
    class Meta:
        model = EmployeeSalary
        fields = '__all__'
# *********** ending Employee Salary Forms****************

# ************ Starting Customer Forms **************
class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = '__all__'

class CustomerLedgerForm(forms.ModelForm):
    class Meta:
        model = CustomerLedger
        fields = '__all__'
# *********** Ending Customer Forms *****************


class InvoiceForm(forms.ModelForm):
    class Meta:
        model = Invoice
        fields = '__all__'


class CarPartsInvoiceForm(forms.ModelForm):
    class Meta:
        model = CarPartsInvoice
        fields = '__all__'


class CarPartsStockoutForm(forms.ModelForm):
    class Meta:
        model = CarPartsStockOut
        fields = '__all__'

philip_inventory/views.py
from django.shortcuts import render

# Create your views here.

templates/philip_inventory/sales/invoice_list.html
{% extends 'philip_inventory/philip_base.html' %}
{% block sales %}active{% endblock %}
{% block sales_list %}active{% endblock %}
{% block content %}
{% load static %}
    <div class="content-wrapper">
    <section class="content-header">
        <ol class="breadcrumb">
            <li><a href="{% url 'common:philip_index' %}"><i class="fa fa-dashboard"></i>Home</a></li>
            <li><a href="{% url 'philip_inventory:add_invoice' %}">Create Invoice</a></li>
            <li class="active">Philippine Invoice List</li>
        </ol>
    </section>
    <br>
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="text-center "><b> Philippine Invoice List</b></h3>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="col-md-3 pull-left">
                                <input type="text" class="form-control name_search" placeholder="Search by Name ..." >
                            </div>
                            <div class="col-md-3">
                                <input type="text" class="form-control id_search" placeholder="Search by Invoice No ...">
                            </div>
                            <div class="col-md-3">
                                <input type="text" class="form-control bill_no" placeholder="Search by Bill No ...">
                            </div>
                            <div class="col-md-3">
                                <input type="date" class="form-control date_search" placeholder="Search by Date ...">
                            </div>
                            <hr>
                            <div class="col-md-2 pull-right">
                                <button class="form-control btn btn-primary search">Search</button>
                            </div>
                        </div>
                    </div>
                    <hr>
                    <div class="box-body">
                        <div class="table-responsive">
                            <table class="table align-items-center table-striped table-bordered table-hover">
                                <thead class="thead-dark">
                                    <tr>
                                        <th>S.No</th>
                                        <th>Date</th>
                                        <th>Invoice</th>
                                        <th>Bill No</th>
                                        <th>Customer</th>
                                        <th>Sub Total</th>
                                        <th>Discount</th>
                                        <th>Grand Total</th>
                                        <th class="text-center">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% if not object_list %}
                                    <tr><td colspan="10" class="text-center">No Invoices Found!</td></tr>
                                {% endif %}
                                {% for invoice in object_list %}
                                    <tr>
                                        {% load humanize %}
                                        <td>{{forloop.counter}}</td>
                                        <td>{{ invoice.date|date:"d M Y" }}</td>
                                        <td>{{ invoice.id|stringformat:"07d" }}</td>
                                        <td>{% if invoice.bill_no %}{{ invoice.bill_no }}{% endif %}</td>
                                        <td>{{ invoice.customer.name|title }}</td>
                                        <td>{{ invoice.sub_total|floatformat:-2|intcomma }}</td>
                                        <td>{{ invoice.discount|floatformat:-2|intcomma }}</td>
                                        <td>{{ invoice.grand_total|floatformat:-2|intcomma }}</td>
                                        <td class="text-center">
                                            <a href="{% url 'philip_inventory:invoice_detail' pk=invoice.id %}"><button class="btn btn-info btn-xs">View</button></a>
                                            <a href="{% url 'philip_inventory:invoice_delete' pk=invoice.id %}" onclick="return confirm('&#9940 Are you sure you want to delete this item &#9940;')"><button class="btn btn-danger btn-xs">Delete</button></a>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                            {% if paginator.page_range|length > 1 %}
                            <div class="text-center col-lg-12">
                                <ul class="pagination justify-content-center">
                                <span class="step-links">
                                    {% if page_obj.has_previous %}
                                        <a href="?page=1">First</a>
                                        <a href="?page={{ page_obj.previous_page_number }}" title="Previous"><<</a>
                                    {% endif %}
                                    {% if page_obj.has_next %}
                                        <a href="?page={{ page_obj.next_page_number }}" title="Next">>></a>
                                        <a href="?page={{ page_obj.paginator.num_pages }}">Last</a>
                                    {% endif %}
                                </span>
                                 </ul>
                            <div>
                            <span class="current">
                                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                            </span>
                            </div>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
{% endblock %}

{% block script %}
    {{ block.super }}
<script>
$(function () {
    $('.search').on('click', function () {
        var url = '{% url "philip_inventory:invoice_list" %}';
        window.location.href  = url + '?' + 'customer_name=' + $('.name_search').val() + '&customer_id=' +  $('.id_search').val() + '&date=' +  $('.date_search').val() + '&bill_no=' +  $('.bill_no').val();
    });
})
</script>

<script>
$('#invoice').on('click', function() {
    var $this = $(this);
  $this.button('loading');
    setTimeout(function() {
       $this.button('reset');
   }, 5000);
});

</script>
<style>
  .pagination a {
  color: black;
  float: left;
  padding: 8px 16px;
  text-decoration: none;
  transition: background-color .3s;
  border: 1px solid #ddd;

}
.pagination a.active {
  background-color: #4CAF50;
  color: white;
  border: 1px solid #4CAF50;
}

.pagination a:hover:not(.active) {background-color: rgb(106, 142, 174);}
</style>
{% endblock %}

templates/philip_inventory/sales/invoice_list_car_parts.html
{% extends 'philip_inventory/philip_base.html' %}
{% block car_parts %}active{% endblock %}
{% block sales_list_car_parts %}active{% endblock %}
{% block content %}

    <div class="content-wrapper">
    <section class="content-header">
        <ol class="breadcrumb">
            <li><a href="{% url 'common:philip_index' %}"><i class="fa fa-dashboard"></i>Home</a></li>
            <li><a href="{% url 'philip_inventory:add_invoice_car_parts' %}">Create Car Parts Invoice</a></li>
            <li class="active">Car Parts Invoice List</li>
        </ol>
    </section>
    <br>
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="text-center "><b>Car Parts Invoice List</b></h3>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="col-md-3 pull-left">
                                <input type="text" class="form-control name_search" placeholder="Search by Name ..." >
                            </div>
                            <div class="col-md-3">
                                <input type="text" class="form-control id_search" placeholder="Search by Invoice No ...">
                            </div>
                            <div class="col-md-3">
                                <input type="text" class="form-control bill_no" placeholder="Search by Bill No ...">
                            </div>
                            <div class="col-md-3">
                                <input type="date" class="form-control date_search" placeholder="Search by Date ...">
                            </div>
                            <hr>
                            <div class="col-md-2 pull-right">
                                <button class="form-control btn btn-primary search">Search</button>
                            </div>
                        </div>
                    </div>
                    <hr>
                    <div class="box-body">
                        <div class="table-responsive">
                            <table class="table align-items-center table-striped table-bordered table-hover">
                                <thead class="thead-dark">
                                    <tr>
                                        <th>S.No</th>
                                        <th>Date</th>
                                        <th>Invoice</th>
                                        <th>Bill No</th>
                                        <th>Customer</th>
                                        <th>Sub Total</th>
                                        <th>Discount</th>
                                        <th>Grand Total</th>
                                        <th class="text-center">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% if not object_list %}
                                    <tr><td colspan="10" class="text-center">No Invoices Found!</td></tr>
                                {% endif %}
                                {% for invoice in object_list %}
                                    <tr>
                                        {% load humanize %}
                                        <td>{{forloop.counter}}</td>
                                        <td>{{ invoice.date|date:"d M Y" }}</td>
                                        <td>{{ invoice.id|stringformat:"07d" }}</td>
                                        <td>{% if invoice.bill_no %}{{ invoice.bill_no }}{% endif %}</td>
                                        <td>{{ invoice.customer.name|title }}</td>
                                        <td>{{ invoice.sub_total|floatformat:-2|intcomma }}</td>
                                        <td>{{ invoice.discount|floatformat:-2|intcomma }}</td>
                                        <td>{{ invoice.grand_total|floatformat:-2|intcomma }}</td>
                                        <td class="text-center">
                                            <a href="{% url 'philip_inventory:invoice_detail_car_parts' pk=invoice.id %}"><button class="btn btn-info btn-xs">View</button></a>
<!--                                            <a href="" onclick="return confirm('&#9940 Are you sure you want to delete this item &#9940;')"><button class="btn btn-danger btn-xs">Delete</button></a>-->
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                            {% if paginator.page_range|length > 1 %}
                            <div class="text-center col-lg-12">
                                <ul class="pagination justify-content-center">
                                <span class="step-links">
                                    {% if page_obj.has_previous %}
                                        <a href="?page=1">First</a>
                                        <a href="?page={{ page_obj.previous_page_number }}" title="Previous"><<</a>
                                    {% endif %}
                                    {% if page_obj.has_next %}
                                        <a href="?page={{ page_obj.next_page_number }}" title="Next">>></a>
                                        <a href="?page={{ page_obj.paginator.num_pages }}">Last</a>
                                    {% endif %}
                                </span>
                                 </ul>
                            <div>
                            <span class="current">
                                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                            </span>
                            </div>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
{% endblock %}

{% block script %}
    {{ block.super }}
<script>
$(function () {
    $('.search').on('click', function () {
        var url = '{% url "philip_inventory:invoice_list_car_parts" %}';
        window.location.href  = url + '?' + 'customer_name=' + $('.name_search').val() + '&customer_id=' +  $('.id_search').val() + '&date=' +  $('.date_search').val() + '&bill_no=' +  $('.bill_no').val();
    });
})
</script>

<script>
$('#invoice').on('click', function() {
    var $this = $(this);
  $this.button('loading');
    setTimeout(function() {
       $this.button('reset');
   }, 5000);
});

</script>
<style>
  .pagination a {
  color: black;
  float: left;
  padding: 8px 16px;
  text-decoration: none;
  transition: background-color .3s;
  border: 1px solid #ddd;

}
.pagination a.active {
  background-color: #4CAF50;
  color: white;
  border: 1px solid #4CAF50;
}

.pagination a:hover:not(.active) {background-color: rgb(106, 142, 174);}
</style>
{% endblock %}