common/urls.py
from .views import IndexView, LoginView, LogoutView, IndexJapanView, IndexPakistanView, IndexPhilipineView
from common.japan_stock_logs import DailyStockLogs, MonthlyStockLogs
from common.pak_stock_logs import PakDailyStockLogs, PakMonthlyStockLogs
from common.philip_stock_logs import PhilipDailyStockLogs, PhilipMonthlyStockLogs
from django.urls import path


urlpatterns = [
    path('', IndexView.as_view(), name='home'),
    path('japan', IndexJapanView.as_view(), name='japan_index'),
    path('pak', IndexPakistanView.as_view(), name='pak_index'),
    path('philip', IndexPhilipineView.as_view(), name='philip_index'),
    path('login', LoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('japan/logs/daily', DailyStockLogs.as_view(), name='daily_logs'),
    path('japan/logs/monthly', MonthlyStockLogs.as_view(), name='monthly_logs'),
    path('pak/logs/daily', PakDailyStockLogs.as_view(), name='pak_daily_logs'),
	path('pak/logs/monthly', PakMonthlyStockLogs.as_view(), name='pak_monthly_logs'),
    path('philip/logs/daily', PhilipDailyStockLogs.as_view(), name='philip_daily_logs'),
	path('philip/logs/monthly', PhilipMonthlyStockLogs.as_view(), name='philip_monthly_logs'),
]

pak_inventory/urls.py
from django.urls import path
from pak_inventory.stock_views import (
    AddCarBrand, CarBrandList, DeleteCarBrand, AddCarStock,
    CarStockList, DeleteCarStock, UpdateCarStockIn, AddCarParts,
    CarPartsList, DeleteCarPartsStock, CarStockOutList
)
from pak_inventory.expense_views import (
    AddExpense, ExpenseList, UpdateExpense, DeleteExpense
)
from pak_inventory.employee_views import (
    AddEmployee, EmployeeList, UpdateEmployee, DeleteEmployee,
    EmployeeSalaryFormView, EmployeeSalaryListView, DeleteEmployeeSalary
)
from pak_inventory.customer_views import (
    AddCustomer, CustomerList, UpdateCustomer, DeleteCustomer, CustomerLedgerListView, DeleteCustomerLedger, DebitCustomerLedgerFormView, CreditCustomerLedgerFormView
)
from pak_inventory.invoice_views import (
    InvoiceListView, CreateInvoiceTemplateView, ProductListAPIView, GenerateInvoiceAPIView, InvoiceDetailTemplateView,
    DeleteInvoice
)
from pak_inventory.bank_views import (AddBank, BankList,DeleteBank, BankLedgerListView, DeleteBankLedger, DebitBankLedgerFormView, CreditBankLedgerFormView)
from pak_inventory.car_parts_invoice_views import (CarPartsInvoiceListView, CarPartsCreateInvoiceTemplateView,CarPartsProductListAPIView, CarPartsGenerateInvoiceAPIView, CarPartsInvoiceDetailTemplateView)

from pak_inventory.reports import (MonthlyReports)


urlpatterns = [
    path('reports/monthly', MonthlyReports.as_view(), name='reports'),
    path('add/expense/', AddExpense.as_view(), name='expense_add'),
    path('list/expense/', ExpenseList.as_view(), name='expense_list'),
    path('delete/expense/<int:pk>/', DeleteExpense.as_view(), name='expense_delete'),
    path('update/expense/<int:pk>/', UpdateExpense.as_view(), name='expense_update'),
    path('add/employee/', AddEmployee.as_view(), name='add_employee'),
    path('list/employee/', EmployeeList.as_view(), name='employee_list'),
    path('update/employee/<int:pk>/', UpdateEmployee.as_view(), name='employee_update'),
    path('delete/employee/<int:pk>/', DeleteEmployee.as_view(), name='employee_delete'),
    path('employee/salary/<int:pk>/', EmployeeSalaryFormView.as_view(), name='employee_salary'),
    path('employee/salary/detail/<int:pk>/', EmployeeSalaryListView.as_view(), name='employee_salary_detail'),
    path('delete/employee/salary/detail/<int:pk>/', DeleteEmployeeSalary.as_view(), name='delete_employee_salary'),
    path('add/car/brand/', AddCarBrand.as_view(), name='add_car_brand'),
    path('list/brand/', CarBrandList.as_view(), name='list_car_brand'),
    path('delete/<int:pk>/', DeleteCarBrand.as_view(), name='delete_car_brand'),
    path('add/car/stock/in/', AddCarStock.as_view(), name='add_car_stockin'),
    path('car/stock/in/list/', CarStockList.as_view(), name='car_stock_list'),
    path('car/stock/out/list/', CarStockOutList.as_view(), name='car_stock_out_list'),
    path('car/stock/<int:pk>/delete/', DeleteCarStock.as_view(), name='delete_car_stockin'),
    path('update/car/<int:pk>/stock/in/', UpdateCarStockIn.as_view(), name='update_car_stockin'),
    path('add/car/parts/', AddCarParts.as_view(), name='add_car_parts'),
    path('list/car/parts/', CarPartsList.as_view(), name='list_car_parts'),
    path('delete/<int:pk>/car/parts/', DeleteCarPartsStock.as_view(), name='delete_car_parts'),
    path('add/customer/', AddCustomer.as_view(), name='add_customer'),
    path('list/customer/', CustomerList.as_view(), name='customer_list'),
    path('update/customer/<int:pk>/', UpdateCustomer.as_view(), name='customer_update'),
    path('delete/customer/<int:pk>/', DeleteCustomer.as_view(), name='customer_delete'),
    path('list/invoice/', InvoiceListView.as_view(), name='invoice_list'),
    path('add/invoice/customer/', CreateInvoiceTemplateView.as_view(), name='add_invoice'),
    path('product/invoice/customer/api/', ProductListAPIView.as_view(), name='product_api'),
    path('generate/invoice/api/', GenerateInvoiceAPIView.as_view(), name='generate_invoice'),
    path("invoice/<int:pk>/detail/", InvoiceDetailTemplateView.as_view(), name='invoice_detail'),
    path("invoice/<int:pk>/delete/", DeleteInvoice.as_view(), name='invoice_delete'),
    path('<int:pk>/ledger/delete', DeleteCustomerLedger.as_view(), name='delete_ledger'),
    path(
        '<int:pk>/ledger/list/',
        CustomerLedgerListView.as_view(),
        name='ledger_list'
    ),
    path(
        '<int:pk>/ledger/debit/',
        DebitCustomerLedgerFormView.as_view(),
        name='ledger_debit'
    ),
    path(
        '<int:pk>/ledger/credit/',
        CreditCustomerLedgerFormView.as_view(),
        name='ledger_credit'
    ),
    path('add/bank/', AddBank.as_view(), name='add_bank'),
    path('list/bank/', BankList.as_view(), name='bank_list'),
    path('delete/bank/<int:pk>/', DeleteBank.as_view(), name='bank_delete'),
    path(
        'bank/<int:pk>/ledger/list/',
        BankLedgerListView.as_view(),
        name='bank_ledger_list'
    ),
    path(
        'bank/<int:pk>/ledger/debit/',
        DebitBankLedgerFormView.as_view(),
        name='bank_ledger_debit'
    ),
    path(
        'bank/<int:pk>/ledger/credit/',
        CreditBankLedgerFormView.as_view(),
        name='bank_ledger_credit'
    ),
    path('bank/<int:pk>/ledger/delete', DeleteBankLedger.as_view(), name='bank_delete_ledger'),
    path('list/invoice/car/parts/sell/', CarPartsInvoiceListView.as_view(), name='invoice_list_car_parts'),
    path('add/invoice/customer/car/parts/', CarPartsCreateInvoiceTemplateView.as_view(), name='add_invoice_car_parts'),
    path('product/invoice/customer/api/car/parts/', CarPartsProductListAPIView.as_view(), name='product_api_car_parts'),
    path('generate/invoice/api/car/parts/', CarPartsGenerateInvoiceAPIView.as_view(), name='generate_invoice_car_parts'),
    path("invoice/<int:pk>/detail/car/parts/", CarPartsInvoiceDetailTemplateView.as_view(), name='invoice_detail_car_parts'),

]

partum_jci/urls.py
from django.contrib import admin
from django.urls import path, include
from common.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('common/', include(('common.urls', 'common'), namespace='common')),
    path('japan/inventory/', include(('japan_inventory.urls', 'japan_inventory'), namespace='japan_inventory')),
    path('philip/inventory/', include(('philip_inventory.urls', 'philip_inventory'), namespace='philip_inventory')),
    path('pak/inventory/', include(('pak_inventory.urls', 'pak_inventory'), namespace='pak_inventory')),
    path('', IndexView.as_view(), name='home'),

]

templates/bank/add_bank.html
{% extends 'base.html' %}
{% block bank %}active{% endblock %}
{% block add_bank %}active{% endblock %}
{% block content %}
{% load static %}

<div class="content-wrapper">
    <section class="content-header">
        <ol class="breadcrumb">
            <li><a href="{% url 'common:japan_index' %}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Japan Add Bank</li>
        </ol>
    </section>
    <br>
    <section class="content">
        <!-- Info boxes -->
        <div class="row">
            <div class="col-md-6">
                <div class="box">
                    <div class="box-header">
                        <h4 class="text-center"><b>Japan Add Bank</b></h4>
                    </div>
                    <div class="box-body">
                        <form action="{% url 'japan_inventory:add_bank' %}" method="post" autocomplete="off">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-12 pull-left form-group">
                                    <label class="form-control-label">Name <span style="color:red">*</span></label>
                                    <input type="text" name="name" class="form-control form-control-alternative" placeholder="Bank Name" required>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12 form-group">
                                    <label class="form-control-label">Branch <span style="color:red"></span></label>
                                    <input type="text" name="Branch" class="form-control form-control-alternative" placeholder="Bank Branch Name">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12 pull-left form-group">
                                    <label class="form-control-label">Account Number <span style="color:red">*</span></label>
                                    <input type="text" name="account_number" class="form-control form-control-alternative" placeholder="Bank Account Number" required>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-4 pull-right form-group">
                                    <label class="form-control-label"></label>
                                    <button type="submit" value="Create" class="btn btn-primary form-control">Save</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

{% endblock %}

templates/bank/add_credit_bank.html
{% extends 'base.html' %}
{% block bank %}active{% endblock %}
{% block bank_list %}active{% endblock %}
{% block content %}
{% load static %}
<div class="content-wrapper">
    <section class="content-header">
        <ol class="breadcrumb">
            <li><a href="{% url 'common:japan_index' %}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="{% url 'japan_inventory:bank_list' %}">Bank List</a></li>
            <li><a href="{% url 'japan_inventory:bank_ledger_list' pk=bank.id %}">Bank Ledger List</a></li>
            <li class="active">Credit/Payment</li>
        </ol>
    </section>
    <br>
    <section class="content">
        <div class="row">
            <div class="col-md-6 pull-left">
                <div class="box">
                    <div class="box-header">
                        <h3 class="text-center"><b>{{ bank.name|title }} |</b> <small><b>Credit Amount</b></small></h3>
                    </div>
                    <div class="box-body">
                        <form action="{% url 'japan_inventory:bank_ledger_debit' pk=bank.id %}" method="post" autocomplete="off">
                            {% csrf_token %}
                            <input type="hidden" name="bank" value="{{ bank.id }}">
                            <div class="row">
                                <div class="col-md-12 pull-left form-group">
                                    <label class="form-control-label">Credit Amount <span style="color:red">*</span></label>
                                    <input type="text" name="credit_amount" class="form-control form-control-alternative" placeholder="Credit Amount" required>
                                </div>
                                <div class="col-md-12 pull-left form-group">
                                    <label class="form-control-label">Date <span style="color:red">*</span></label>
                                    <input type="date" name="date" class="form-control" required>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12 pull-left form-group">
                                    <label class="form-control-label">Details <span style="color:red">*</span></label>
                                    <textarea type="text" name="details" class="form-control form-control-alternative" placeholder="Details" required></textarea>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-4 pull-right form-group">
                                    <label class="form-control-label"></label>
                                    <button type="submit" value="Create" class="btn btn-primary form-control">Save</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
{% endblock %}

templates/bank/add_debit_bank.html
{% extends 'base.html' %}
{% block bank %}active{% endblock %}
{% block bank_list %}active{% endblock %}
{% block content %}
{% load static %}
<div class="content-wrapper">
    <section class="content-header">
        <ol class="breadcrumb">
            <li><a href="{% url 'common:japan_index' %}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="{% url 'japan_inventory:bank_list' %}">Bank List</a></li>
            <li><a href="{% url 'japan_inventory:bank_ledger_list' pk=bank.id %}">Bank Ledger List</a></li>
            <li class="active">Debit/Payment</li>
        </ol>
    </section>
    <br>
    <section class="content">
        <div class="row">
            <div class="col-md-6 pull-left">
                <div class="box">
                    <div class="box-header">
                        <h3 class="text-center"><b>{{ bank.name|title }} |</b> <small><b>Debit Amount</b></small></h3>
                    </div>
                    <div class="box-body">
                        <form action="{% url 'japan_inventory:bank_ledger_debit' pk=bank.id %}" method="post" autocomplete="off">
                            {% csrf_token %}
                            <input type="hidden" name="bank" value="{{ bank.id }}">
                            <div class="row">
                                <div class="col-md-12 pull-left form-group">
                                    <label class="form-control-label">Debit Amount <span style="color:red">*</span></label>
                                    <input type="text" name="debit_amount" class="form-control form-control-alternative" placeholder="Debit Amount" required>
                                </div>
                                <div class="col-md-12 pull-left form-group">
                                    <label class="form-control-label">Date <span style="color:red">*</span></label>
                                    <input type="date" name="date" class="form-control" required>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12 pull-left form-group">
                                    <label class="form-control-label">Details <span style="color:red">*</span></label>
                                    <textarea type="text" name="details" class="form-control form-control-alternative" placeholder="Details" required></textarea>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-4 pull-right form-group">
                                    <label class="form-control-label"></label>
                                    <button type="submit" value="Create" class="btn btn-primary form-control">Save</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
{% endblock %}

templates/bank/bank_ledger_list.html
{% extends 'base.html' %}
{% block bank %}active{% endblock %}
{% block bank_list %}active{% endblock %}
{% block content %}
{% load static %}
<div class="content-wrapper">
    <section class="content-header">
        <a href="{% url 'japan_inventory:bank_ledger_debit' pk=bank.id %}"><button type="button" value="Create" class="btn btn-success">Debit (Ledger)</button></a>
        <a href="{% url 'japan_inventory:bank_ledger_credit' pk=bank.id %}"><button type="button" value="Create" class="btn btn-danger">Credit (Payment))</button></a>
        <ol class="breadcrumb">
            <li><a href="{% url 'common:japan_index' %}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="{% url 'japan_inventory:bank_list' %}">Bank List</a></li>
            <li class="active">Ledger</li>
        </ol>
    </section>
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="text-center"><b>{{ bank.name|title }} |</b> <small><b>Ledger Statement</b></small></h3>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="col-md-4">
                                <input type="date" class="form-control date_search" placeholder="Search by Date ..." >
                            </div>
                            <div class="col-md-2">
                                <button class="form-control btn btn-primary search">Search</button>
                            </div>
                            <div class="col-md-6" style="text-align: right">
                                <strong class="text-center" style="font-size: 25px; color: red"> Total Account Balance: {{bank.total_debit_amount|floatformat:-2 }} </strong>
                            </div>
                        <br><br>
                        <hr>
                        </div>
                    </div>
                    <div class="box-body">
                        <div class="table-responsive">
                            <table class="table align-items-center table-striped table-bordered table-hover">
                                <thead class="thead-dark">
                                <tr>
                                    <th>S.No</th>
                                    <th>Date</th>
                                    <th>Detail</th>
                                    <th><small>Debit/Ledger Amount</small></th>
                                    <th><small>Credit/Payment Amount</small></th>
                                    <th class="text-center">Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for ledger in object_list %}
                                <tr>
                                    {% load humanize %}
                                    <td>{{forloop.counter}}</td>
                                    <td>{{ledger.date|date:"d M Y"}}</td>
                                    <td>{{ledger.details}}</td>
                                    <td>{{ledger.debit_amount|floatformat:-2|intcomma }}</td>
                                    <td>{{ledger.credit_amount|floatformat:-2|intcomma }}</td>
                                    <td class="text-center">
                                        <a href="{% url 'japan_inventory:bank_delete_ledger' pk=ledger.id %}" onclick="return confirm('&#9940 Are you sure you want to delete this item &#9940;')"><button class="btn btn-danger btn-xs">Delete</button></a>
                                    </td>
                                </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                            {% if paginator.page_range|length > 1 %}
                            <div class="text-center col-lg-12">
                                <ul class="pagination justify-content-center">
                                <span class="step-links">
                                    {% if page_obj.has_previous %}
                                        <a href="?page=1">First</a>
                                        <a href="?page={{ page_obj.previous_page_number }}" title="Previous"><<</a>
                                    {% endif %}
                                    {% if page_obj.has_next %}
                                        <a href="?page={{ page_obj.next_page_number }}" title="Next">>></a>
                                        <a href="?page={{ page_obj.paginator.num_pages }}">Last</a>
                                    {% endif %}
                                </span>
                                 </ul>
                            <div>
                            <span class="current">
                                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                            </span>
                            </div>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
{% endblock %}

{% block script %}
    {{ block.super }}
<script>
$(function () {
    $('.search').on('click', function () {
        var url = '{% url "japan_inventory:bank_ledger_list" pk=bank.id %}';
        window.location.href  = url + '?' + 'date=' + $('.date_search').val();
    });
})
</script>
<style>
  .pagination a {
  color: black;
  float: left;
  padding: 8px 16px;
  text-decoration: none;
  transition: background-color .3s;
  border: 1px solid #ddd;

}
.pagination a.active {
  background-color: #4CAF50;
  color: white;
  border: 1px solid #4CAF50;
}

.pagination a:hover:not(.active) {background-color: rgb(106, 142, 174);}
</style>
{% endblock %}

templates/bank/bank_list.html
{% extends 'base.html' %}
{% block bank %}active{% endblock %}
{% block bank_list %}active{% endblock %}
{% block content %}
{% load static %}

<div class="content-wrapper">
    <section class="content-header">
        <ol class="breadcrumb">
            <li><a href="{% url 'common:japan_index' %}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="{% url 'japan_inventory:add_bank' %}">Add Bank</a></li>
            <li class="active">Japan Bank List</li>
        </ol>
    </section>
    <br>
    <section class="content">
        <div class="row">
            <div class="col-lg-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="text-center"><b>Japan Bank List</b></h3>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="col-md-4 pull-left">
                                <input type="text" class="form-control name_search" placeholder="Search by Bank Name ..." >
                            </div>
                            <div class="col-md-4">
                                <input type="text" class="form-control id_search" placeholder="Search by Account Num ...">
                            </div>
                            <div class="col-md-2 pull-right">
                                <button class="form-control btn btn-primary search">Search</button>
                            </div>
                        <br><br>
                        <hr>
                        </div>
                    </div>
                    <div class="box-body">
                        <div class="table-responsive">
                            <table class="table align-items-center table-striped table-bordered table-hover">
                                <thead class="thead-dark">
                                <tr>
                                    <th>S.No</th>
                                    <th>Name</th>
                                    <th>Branch</th>
                                    <th>Account Number</th>
                                    <th class="text-center">Action</th>
                                    <th class="text-center">Ledger</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for bank in object_list %}
                                <tr>
                                    <td>{{forloop.counter}}</td>
                                    <td>{{bank.name|title}}</td>
                                    <td>{{bank.Branch|title}}</td>
                                    <td>{{bank.account_number}}</td>
                                    <td class="text-center">
                                        <a href="{% url 'japan_inventory:bank_delete' pk=bank.id %}" onclick="return confirm('&#9940 Are you sure you want to delete this &#9940;')"><button class="btn btn-danger btn-xs">Delete</button></a>
                                    </td>
                                    <td class="text-center">
                                         <a href="{% url 'japan_inventory:bank_ledger_list' pk=bank.id %}"><button class="btn btn-success btn-xs">Bank Ledger</button></a>
                                    </td>
                                </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                            {% if paginator.page_range|length > 1 %}
                            <div class="text-center col-lg-12">
                                <ul class="pagination justify-content-center">
                                <span class="step-links">
                                    {% if page_obj.has_previous %}
                                        <a href="?page=1">First</a>
                                        <a href="?page={{ page_obj.previous_page_number }}" title="Previous"><<</a>
                                    {% endif %}
                                    {% if page_obj.has_next %}
                                        <a href="?page={{ page_obj.next_page_number }}" title="Next">>></a>
                                        <a href="?page={{ page_obj.paginator.num_pages }}">Last</a>
                                    {% endif %}
                                </span>
                                 </ul>
                            <div>
                            <span class="current">
                                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                            </span>
                            </div>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
{% endblock %}
{% block script %}
    {{ block.super }}
<script>
$(function () {
    $('.search').on('click', function () {
        var url = '{% url "japan_inventory:bank_list" %}';
        window.location.href  = url + '?' + 'name=' + $('.name_search').val() + '&bank_id=' +  $('.id_search').val();
    });
})
</script>
<style>
  .pagination a {
  color: black;
  float: left;
  padding: 8px 16px;
  text-decoration: none;
  transition: background-color .3s;
  border: 1px solid #ddd;

}
.pagination a.active {
  background-color: #4CAF50;
  color: white;
  border: 1px solid #4CAF50;
}

.pagination a:hover:not(.active) {background-color: rgb(106, 142, 174);}
</style>
{% endblock %}